slug = "another-test"
title = "Ullamcorper Tempor"
description = "consectetur adipiscing "
author = "Magnis Tempus"
date = "2024-09-30T07:48:04.945Z"
location = "src/blog_example/content/posts/1727682484_another-test/post.djot"
