slug = "fourth"
title = "Vitae Risus"
description = "Nunc vitae risus mollis, consequat risus sit amet."
author = "Magnis Tempus"
date = "2024-10-04T04:13:09.965Z"
location = "src/blog_example/content/posts/1728015189_fourth/post.djot"
