slug = "first"
title = "Eleifend Tempus"
description = "dolor sit amet"
author = "Magnis Tempus"
date = "2024-09-29T10:59:51.425Z"
location = "src/blog_example/content/posts/1727607591_first/post.djot"
